### ISSUE TITLE
Bump selfsigned to 2.0.0 to fix vulnerability with node-forge

### ISSUE THREAD

**Issue by pascalmtts** [unjs/listhen#11]
The dependency "selfsigned" used the dependency "node-forge" which had a vulnerability. This has been fixed in version 2.0.0. Could you update the dependency for this?

**Comment by pi0** [comment]
Hi @pascalmtts. I think dependency is bumped also with `1.10.13` but will update to 2.x 👍 

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/5158436/149141080-42b2cd8a-b252-4812-a001-9552ff7dbee4.png">

**Comment by pascalmtts** [comment]
You are right, I have not even paid attention to which version that was fixed. Thank you!

**Comment by pi0** [comment]
Updated in 0.2.6
