### ISSUE TITLE
Doesn't seem to work with ViteDevServer

### ISSUE THREAD

**Issue by chriscalo** [unjs/listhen#12]
Minimal reproduction:

```js
const { createServer } = require("vite");
const { listen } = require("listhen");

(async function main() {
  listen(await createServer());
})();
```

Output:

```
ViteDevServer.app is deprecated. Use ViteDevServer.middlewares instead.

  > Local:    http://localhost:4000/ 
  > Network:  http://192.168.1.203:4000/
  > Network:  http://192.168.86.31:4000/
```

Attempts to open `http://localhost:4000/` hang forever. Trying `listen((await createServer()).middlewares)` also doesn't work.

**Comment by Atinux** [comment]
Sorry for the late answer @chriscalo 

Is it still broken with latest vite?

**Comment by chriscalo** [comment]
Apologies, I gave up on listhen a long time ago after hitting this problem. But the full reproduction is in my first comment, so you should be able to try it out yourself and see if it's still broken.

**Comment by pi0** [comment]
This should work:

https://stackblitz.com/edit/node-yvmx9e?file=index.js,package.json

```js
const { createServer } = require('vite');
const { listen } = require('listhen');

(async function main() {
  const viteServer = await createServer();
  await listen((req, res) => {
    viteServer.middlewares.handle(req, res);
  });
})();
```

(We need to create a wrapper handler as `middlewares.handle` has a bound context). 

Hope it helps.

**Comment by chriscalo** [comment]
Thanks for the working sample code! 🥳

(Since Vite is such an important tool in the ecosystem, consider whether it would help to put this example in the README. I just assumed listhen was broken when it wouldn't work on my first try.)

**Comment by pi0** [comment]
It is an advanced usecase but also would be nice example to add to the readme /cc @patak @antfu i hope it is a good usage to mention for you too.
