### ISSUE TITLE
Open the URL in the browser - uncaughtException in WSL environment

### ISSUE THREAD

**Issue by jensk** [unjs/listhen#123]
### Environment

Operating System: WSL2
Node Version: v18.17.1
Package Manager: pnpm@8.7.5

### Reproduction

I don´t know how to create a one click reproduction for this issue since it is heavily related to WSL. 

This is my WSL configuration file:

`
ls -al /etc/wsl.conf
`

-rw-r--r-- 1 root root 531 Sep 12 10:07 /etc/wsl.conf

`
cat /etc/wsl.conf
`

[network]
generateHosts = false

### Describe the bug

I am coming from nuxt and I get the following error when starting the dev server:

` ERROR  [uncaughtException] spawn function getWslDrivesMountPoint2() {`

I tried to clone this repository directly and was able to reproduce the error with the following commands:

`
pnpm install
`

`pnpm play --open
`

I guess listhen tries to detect the wsl mount point and is somehow failing. I'm looking at the code for a while but cant figure out what exactly is going wrong.

Despite the error, everything works fine, only the browser does not open.

**Comment by stafyniaksacha** [comment]
The code responsible for the issue come from here: https://github.com/unjs/listhen/blob/da86eaac12121ad186c9dc5d8e9e415924b74bb9/src/lib/open.ts#L41-L43

Another approach with wsl to open browser is to run (through bash/zsh/...) `explorer.exe http://localhost:3000/`
