### ISSUE TITLE
Capturing H3 errors

### ISSUE THREAD

**Issue by nainemom** [unjs/listhen#163]
### Environment

os: `linux mint `
nodejs: `v20.8.1`
listhen: `^1.7.2`
h3: `^1.11.1`

### Reproduction

https://gist.github.com/nainemom/93650c8efe74714e0fb6ba4193adc2f5

### Describe the bug

`onError` prop on `h3` app never reaches when the app started by `listhen`.

### Additional context

I tried to use `onError` prop on `h3` app object to capture my application error, however it doesn't run my error handler function at all. at first, I thought that it may be the `h3` bug, but after few more tests, i realized that it's actually related to `listhen`.

In the reproduction gist, i created two script, one of them starts the app with `listhen` and the other one just start the app with `nodejs` itself and create web server with nodejs `http` module.
The app itself is so simple, just a simple `/error` route to throw an error.
Now if you try to use `listhen` to start the app, the error handler method never reaches, but with `node` it just works.

I also thought that it may tty mapping problem, but it seems not.

**Comment by pi0** [comment]
Thanks for detailed issue. It is linked with https://github.com/unjs/listhen/issues/111
