### ISSUE TITLE
Add a config option to configure the interface the server should bind.

### ISSUE THREAD

**Issue by dSchaexn** [unjs/listhen#72]
### Describe the feature

Currently one can set the hostname. But for example if i set docs.wesense.develop it will bind automatically to 127.0.0.1 which is not not wanted in a proxied environment.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. Host/Hostname will be resolved by listhen>node>os to the IP address and used to determine which network interface(s) to listen on. It is not a host/domain matcher like the one in reverse proxies. You can set it to `0.0.0.0` or server public IP address based on needs.
