### ISSUE TITLE
Version 1.1.2 has compatibility issues with the consola plugin

### ISSUE THREAD

**Issue by baoxianggao** [unjs/listhen#76]
### Environment

14.21

### Reproduction

no need

### Describe the bug

hi,
  I'm using this plugin that nuxt-windicss depends on，my consola.js version is 3.1.0, when i run my project, i get this error:
Package subpath './utils' is not defined by "exports" in D:\code\enterprise-front-ui\node_modules\consola\package.json imported from D:\code\enterprise-front-ui\node_modules\listhen\dist\index.mjs
  it seems 3.1.0 version not exports utils.js ,I solved this problem by upgrading the version to 3.2.3, I hope it can be compatible to prevent other people from having this error， thank you so much!

**Comment by pi0** [comment]
Hi. Can you please try to remove lock file and `node_modules` and trying again? It might be because of a wrongly hoisted version of consola not supporting `/utils`.

**Comment by baoxianggao** [comment]
> 你好。您可以尝试删除锁定文件并重`node_modules`试吗？这可能是因为错误提升的 consola 版本不支持`/utils`.

in my project, i have lock version in my package.json before:
"overrides": {
    "consola": "3.1.0",
    }
 That's because there was a problem that the project package failed due to the version upgrade. Developers cannot avoid project errors caused by automatic version upgrades of plugins, so I choose to lock the version.It's not an option I would prefer, but there are no other options.

**Comment by baoxianggao** [comment]
The upgrade version is of course feasible, I mean it would be better if the old version can be considered， thank you very much!

**Comment by pi0** [comment]
Usually we use caret ranges `^3.x.y` in dependencies of `listhen` and other packages to indicate latest in `3.x` line is desired. Do you have any specific issues with consola that need to pin it and cannot upgrade? (please report it in consola if any 👍🏼 )
